[package]
name = "neolith"
version = "0.1.0"
description = "Hotline protocol implementation"
homepage = "https://github.com/jyelloz/neolith"
repository = "https://github.com/jyelloz/neolith.git"
authors = ["Jordan Yelloz <jordan@yelloz.me>"]
edition = "2024"
license = "MIT"
default-run = "nlserver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
async-compat = "0.2"
async-fs = "2"
async-stream = "0.3"
clap = { version = "4", features = ["derive"] }
deku = "0.20"
derive_more = { version = "2", features = ["full"] }
dialoguer = "*"
encoding_rs = "0.8"
enumset = { version = "*", features = ["serde"] }
four-cc = "*"
futures = "0.3"
futures-lite = "2"
listenfd = "1"
magic = "0.16"
maplit = "1"
num_enum = "0.7"
pwhash = "1"
regex = "1"
serde = { version = "*", features = ["derive"] }
strum = { version = "*", features = ["derive"] }
thiserror = "*"
time = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }
toml = "*"
tower = { version = "0.5", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
[dependencies.adfs]
git = "https://iris.radicle.xyz/zGUcPta6ndSN6JjNfMpecKHrnLQk.git"
rev = "205117a49f668e965ecc0c321c15adbec46fd27a"
features = ["async"]

